version: 1

languages:
  - javascript
  - typescript
  - vue
  - json
  - yaml

prompts:
  - description: >
      This is a Nuxt 3 project using TypeScript, Pinia for state management, i18n with multiple locales.
      Components should be built using Vue 3's Composition API and <script setup>. Tailwind CSS is used for styling.
    files:
      - nuxt.config.ts
      - tailwind.config.ts
      - tsconfig.json
      - .env
      - package.json

style:
  indentation: 2
  semi: false
  quotes: single
